services:
  # ──────────────────────────────────────────────
  # MySQL Database Service
  # ──────────────────────────────────────────────
  mysql:
    image: mysql:8.0
    container_name: lngw_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lngw2025_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: gywo9988!@
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # ──────────────────────────────────────────────
  # 1) app: Next.js + Express(동시 실행) + Webhook (포트 7000)
  # ──────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: lngw_app
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3201
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_PASSWORD=gywo9988!@
      - DB_NAME=lngw2025_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3201:3201" # Next.js
      - "5000:5000" # Express
      - "7000:7000" # Webhook 서버
    depends_on:
      - mysql

  # ──────────────────────────────────────────────
  # 2) nginx: HTTPS(SSL) 리버스 프록시
  # ──────────────────────────────────────────────
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: lngw2025_v2-nginx
    container_name: lngw_nginx
    restart: always
    depends_on:
      - app
      - acme-cron
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client-nextjs/.next:/app/client-nextjs/.next:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
      - ./nginx/html:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # ──────────────────────────────────────────────
  # 3) acme: Let's Encrypt 기반 인증서 최초 발급
  # ──────────────────────────────────────────────
  acme:
    image: neilpang/acme.sh
    container_name: acme
    volumes:
      - ./nginx/certs:/etc/nginx/ssl
      - ./nginx/html:/var/www/html
      - ~/.acme.sh:/home/acme/.acme.sh
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PUID=1000
      - PGID=1000
    entrypoint:
      - "sh"
      - "-c"
      - |
        # 1) Let's Encrypt를 기본 CA로 설정
        acme.sh --set-default-ca --server letsencrypt

        # 2) 인증서 발급
        acme.sh --issue \
          --webroot /var/www/html \
          -d gw.lnpartners.biz \
          --keypath /etc/nginx/ssl/gw.lnpartners.biz.key \
          --fullchainpath /etc/nginx/ssl/gw.lnpartners.biz.cer \
          --reloadcmd "docker-compose exec nginx nginx -s reload"

        # 발급 후 스크립트 종료

  # ──────────────────────────────────────────────
  # 4) acme-cron: 주기적 인증서 갱신 서비스
  # ──────────────────────────────────────────────
  acme-cron:
    image: neilpang/acme.sh
    container_name: acme_cron
    volumes:
      - ./nginx/certs:/etc/nginx/ssl
      - ./nginx/html:/var/www/html
      - ~/.acme.sh:/home/acme/.acme.sh
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PUID=1000
      - PGID=1000
    entrypoint:
      - "sh"
      - "-c"
      - |
        while true; do
          acme.sh --cron --home /home/acme/.acme.sh \
            --reloadcmd "docker-compose exec nginx nginx -s reload"
          sleep 12h
        done
    restart: always
