version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lngw2025_v2_server
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: lngw2025_db
      DB_USER: appuser
      DB_PASSWORD: gywo9988!@
      PORT: 4000
    ports:
      - "3000:4000"
    restart: always

volumes:
  mysql-data:
