"use client";

import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  ko: {
    // 앱 공통
    "app.title": "LN Partners 그룹웨어",
    "app.redirecting": "로딩 중입니다...",

    // 공통
    login: "로그인",
    register: "회원가입",
    logout: "로그아웃",
    dashboard: "대시보드",
    customers: "고객",
    "customers.list": "고객 목록",
    "customers.add": "고객 등록",
    "customers.voc": "VOC 관리",
    "customers.history": "활동 이력",
    "customers.grades": "등급 관리",
    "customers.searchAndFilter": "검색 및 필터",
    "customers.searchPlaceholder": "회사명, 담당자, 업종으로 검색...",
    "customers.allGrades": "모든 등급",
    "customers.gradeA": "A등급 (VIP)",
    "customers.gradeB": "B등급 (우수)",
    "customers.gradeC": "C등급 (일반)",
    "customers.addNew": "새 고객 등록",
    "customers.total": "전체 고객",
    "customers.contact": "담당자",
    "customers.industry": "업종",
    "customers.registeredDate": "등록일",
    "customers.viewDetails": "상세보기",
    "customers.edit": "수정",
    "customers.activityHistory": "활동이력",
    "customers.noResults": "검색 조건에 맞는 고객이 없습니다.",
    "customers.addFirst": "첫 번째 고객 등록하기",
    "customers.add.description":
      "새로운 고객 정보를 등록하여 고객 데이터베이스를 확장하세요",
    "customers.add.basicInfo.title": "기본 정보",
    "customers.add.basicInfo.description": "고객의 기본 정보를 입력하세요",
    "customers.add.companyName": "회사명",
    "customers.add.companyName.placeholder": "회사명을 입력하세요",
    "customers.add.contactName": "담당자명",
    "customers.add.contactName.placeholder": "담당자명을 입력하세요",
    "customers.add.email": "이메일",
    "customers.add.email.placeholder": "이메일 주소를 입력하세요",
    "customers.add.phone": "전화번호",
    "customers.add.phone.placeholder": "전화번호를 입력하세요",
    "customers.add.industry": "업종",
    "customers.add.industry.placeholder": "업종을 입력하세요",
    "customers.add.grade": "고객 등급",
    "customers.add.address": "주소",
    "customers.add.address.placeholder": "주소를 입력하세요",
    "customers.grade.A": "A등급 (VIP)",
    "customers.grade.B": "B등급 (우수)",
    "customers.grade.C": "C등급 (일반)",
    "customers.add.companyType": "회사 유형",
    "customers.add.companyType.placeholder": "회사 유형을 선택하세요",
    "customers.add.companyType.customPlaceholder": "회사 유형을 입력하세요",
    "customers.add.grade.placeholder": "등급을 선택하세요",
    "customers.add.grade.customPlaceholder": "등급을 입력하세요",
    "customers.companyType.small": "중소기업",
    "customers.companyType.large": "대기업",
    "customers.companyType.startup": "스타트업",
    "customers.companyType.public": "공공기관",
    "customers.companyType.nonprofit": "비영리단체",
    "common.directInput": "직접 입력",
    "common.error": "오류가 발생했습니다",

    // 글로벌 에러 메시지
    "globalError.title": "시스템 오류",
    "globalError.description": "예상치 못한 오류가 발생했습니다. 다시 시도해주세요.",
    "globalError.retry": "다시 시도",

    // 네비게이션
    "navigation.dashboard": "대시보드",
    "navigation.customers": "고객 관리",
    "navigation.products": "상품 관리",
    "navigation.marketing": "마케팅",
    "navigation.settings": "설정",
    "navigation.sales": "영업",
    "navigation.revenue": "수익",
    "navigation.accounting": "회계",
    "navigation.employees": "직원",
    "navigation.profile": "프로필",

    // 사이드바
    "sidebar.companyName": "LN Partners",
    "sidebar.subTitle": "그룹웨어",
    "sidebar.menuTitle": "메뉴",

    // 기타 필요한 번역들
    products: "제품",
    "products.list": "제품 목록",
    "products.add": "제품 등록",
    "products.categories": "카테고리 관리",
    "products.models": "모델 관리",
    "products.competitors": "경쟁사 정보",
    "products.inventory": "재고 관리",
    sales: "영업관리",
    "sales.dashboard": "영업 대시보드",
    "sales.opportunities": "영업기회",
    "sales.pipeline": "영업 파이프라인",
    "sales.quotes": "견적서",
    "sales.activities": "영업 활동",
    "sales.kpi": "영업 성과",
    revenue: "매출관리",
    "revenue.dashboard": "매출 대시보드",
    "revenue.record": "매출 기록",
    "revenue.quotes": "견적서 관리",
    "revenue.orders": "발주 관리",
    "revenue.payment": "입금 관리",
    "revenue.statistics": "매출 통계",
    "revenue.goals": "목표 대비 실적",
    marketing: "마케팅",
    "marketing.dashboard": "마케팅 대시보드",
    "marketing.content": "콘텐츠 관리",
    "marketing.monitoring": "모니터링",
    "marketing.insights": "인사이트",
    "marketing.abtest": "A/B 테스트",
    "marketing.trends": "트렌드 분석",
    "marketing.engagement": "참여도 관리",
    "marketing.brandStrategy": "브랜드 전략",
    "marketing.marketAnalysis": "시장 및 경쟁 분석",
    "marketing.planningProcess": "마케팅 계획 및 프로세스",
    "marketing.campaignCalendar": "캠페인 캘린더",
    "marketing.contentLibrary": "콘텐츠 라이브러리",
    "marketing.influencerManagement": "인플루언서",
    "marketing.budgetExpense": "예산·지출 관리",
    "marketing.settings": "설정",

    accounting: "회계 관리",
    "accounting.dashboard": "회계 대시보드",
    "accounting.voucher": "전표 관리",
    "accounting.ledger": "원장 관리",
    "accounting.statements": "재무제표",
    "accounting.assets": "자산 관리",
    "accounting.tax": "세무 관리",
    "accounting.budget": "예산 관리",
    "accounting.reports": "회계 보고서",

    employees: "직원 관리",
    "employees.dashboard": "직원 대시보드",
    "employees.leave": "휴가 관리",
    "employees.salary": "급여 관리",
    "employees.profile": "직원 프로필",
    "employees.attendance": "근태 관리",
    "employees.evaluation": "성과 평가",
    "employees.communication": "공지사항",

    settings: "설정",
    "settings.dashboard": "설정 센터",
    "settings.accessControl": "접근제어 관리",
    "settings.general": "일반 설정",
    "settings.profile": "프로필 설정",
    "settings.notifications": "알림 설정",
    "settings.integrations": "연동 설정",
    "settings.workflows": "워크플로우",
    "settings.dataManagement": "데이터 관리",
    "settings.auditLogs": "감사 로그",
    "settings.billing": "결제 및 구독",

    profile: "프로필",
    loading: "로딩 중...",
  },
  vi: {
    // 앱 공통
    "app.title": "LN Partners Groupware",
    "app.redirecting": "Đang tải...",

    // 공통
    login: "Đăng nhập",
    register: "Đăng ký",
    logout: "Đăng xuất",
    dashboard: "Bảng điều khiển",
    customers: "Khách hàng",
    "customers.list": "Danh sách khách hàng",
    "customers.add": "Thêm khách hàng",
    "customers.voc": "Quản lý phản hồi khách hàng (VOC)",
    "customers.history": "Lịch sử hoạt động khách hàng",
    "customers.grades": "Quản lý cấp độ khách hàng",
    "customers.searchAndFilter": "Tìm kiếm & Lọc",
    "customers.searchPlaceholder":
      "Tìm kiếm theo tên công ty, người liên hệ, ngành nghề...",
    "customers.allGrades": "Tất cả cấp độ",
    "customers.gradeA": "Cấp A (VIP)",
    "customers.gradeB": "Cấp B (Xuất sắc)",
    "customers.gradeC": "Cấp C (Thường)",
    "customers.addNew": "Thêm khách hàng mới",
    "customers.total": "Tổng khách hàng",
    "customers.contact": "Người liên hệ",
    "customers.industry": "Ngành nghề",
    "customers.registeredDate": "Ngày đăng ký",
    "customers.viewDetails": "Xem chi tiết",
    "customers.edit": "Chỉnh sửa",
    "customers.activityHistory": "Lịch sử hoạt động",
    "customers.noResults":
      "Không có khách hàng nào phù hợp với tiêu chí tìm kiếm.",
    "customers.addFirst": "Đăng ký khách hàng đầu tiên",
    "customers.add.description":
      "Đăng ký thông tin khách hàng mới để mở rộng cơ sở dữ liệu khách hàng",
    "customers.add.basicInfo.title": "Thông tin cơ bản",
    "customers.add.basicInfo.description":
      "Nhập thông tin cơ bản của khách hàng",
    "customers.add.companyName": "Tên công ty",
    "customers.add.companyName.placeholder": "Nhập tên công ty",
    "customers.add.contactName": "Tên người liên hệ",
    "customers.add.contactName.placeholder": "Nhập tên người liên hệ",
    "customers.add.email": "Email",
    "customers.add.email.placeholder": "Nhập địa chỉ email",
    "customers.add.phone": "Số điện thoại",
    "customers.add.phone.placeholder": "Nhập số điện thoại",
    "customers.add.industry": "Ngành nghề",
    "customers.add.industry.placeholder": "Nhập ngành nghề",
    "customers.add.grade": "Cấp độ khách hàng",
    "customers.add.address": "Địa chỉ",
    "customers.add.address.placeholder": "Nhập địa chỉ",
    "customers.grade.A": "Hạng A (VIP)",
    "customers.grade.B": "Hạng B (Tốt)",
    "customers.grade.C": "Hạng C (Thường)",
    "customers.add.companyType": "Loại công ty",
    "customers.add.companyType.placeholder": "Chọn loại công ty",
    "customers.add.companyType.customPlaceholder": "Nhập loại công ty",
    "customers.add.grade.placeholder": "Chọn hạng khách hàng",
    "customers.add.grade.customPlaceholder": "Nhập hạng khách hàng",
    "customers.companyType.small": "Doanh nghiệp nhỏ",
    "customers.companyType.large": "Tập đoàn lớn",
    "customers.companyType.startup": "Công ty khởi nghiệp",
    "customers.companyType.public": "Cơ quan công",
    "customers.companyType.nonprofit": "Tổ chức phi lợi nhuận",
    "common.directInput": "Nhập trực tiếp",
    "common.error": "Đã xảy ra lỗi",

    // 글로벌 에러 메시지
    "globalError.title": "Lỗi hệ thống",
    "globalError.description": "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.",
    "globalError.retry": "Thử lại",

    // 네비게이션
    "navigation.dashboard": "Bảng điều khiển",
    "navigation.customers": "Khách hàng",
    "navigation.products": "Sản phẩm",
    "navigation.marketing": "Marketing",
    "navigation.settings": "Cài đặt",
    "navigation.sales": "Bán hàng",
    "navigation.revenue": "Doanh thu",
    "navigation.accounting": "Kế toán",
    "navigation.employees": "Nhân viên",
    "navigation.profile": "Hồ sơ",

    // 사이드바
    "sidebar.companyName": "LN Partners",
    "sidebar.subTitle": "Groupware",
    "sidebar.menuTitle": "Menu",

    // 기타 필요한 번역들
    products: "Sản phẩm",
    "products.list": "Danh sách sản phẩm",
    "products.add": "Đăng ký sản phẩm",
    "products.categories": "Quản lý danh mục",
    "products.models": "Quản lý mô hình",
    "products.competitors": "Thông tin đối thủ",
    "products.inventory": "Quản lý kho",
    sales: "Quản lý bán hàng",
    "sales.dashboard": "Bảng điều khiển bán hàng",
    "sales.opportunities": "Cơ hội bán hàng",
    "sales.pipeline": "Quy trình bán hàng",
    "sales.quotes": "Báo giá",
    "sales.activities": "Hoạt động bán hàng",
    "sales.kpi": "Hiệu suất bán hàng",
    revenue: "Quản lý doanh thu",
    "revenue.dashboard": "Bảng điều khiển doanh thu",
    "revenue.record": "Ghi nhận doanh thu",
    "revenue.quotes": "Quản lý báo giá",
    "revenue.orders": "Quản lý đơn hàng",
    "revenue.payment": "Quản lý thanh toán",
    "revenue.statistics": "Thống kê doanh thu",
    "revenue.goals": "Thành tích so với mục tiêu",
    marketing: "Marketing",
    "marketing.dashboard": "Bảng điều khiển Marketing",
    "marketing.content": "Quản lý Nội dung",
    "marketing.monitoring": "Giám sát",
    "marketing.insights": "Thông tin chi tiết",
    "marketing.abtest": "Kiểm tra A/B",
    "marketing.trends": "Phân tích Xu hướng",
    "marketing.engagement": "Quản lý Tương tác",
    "marketing.brandStrategy": "Chiến lược Thương hiệu",
    "marketing.marketAnalysis": "Phân tích Thị trường & Đối thủ",
    "marketing.planningProcess": "Kế hoạch & Quy trình Marketing",
    "marketing.campaignCalendar": "Lịch Chiến dịch",
    "marketing.contentLibrary": "Thư viện Nội dung",
    "marketing.influencerManagement": "Quản lý Influencer",
    "marketing.budgetExpense": "Ngân sách & Chi phí",
    "marketing.settings": "Cài đặt",

    accounting: "Quản lý kế toán",
    "accounting.dashboard": "Bảng điều khiển kế toán",
    "accounting.voucher": "Quản lý chứng từ",
    "accounting.ledger": "Quản lý sổ cái",
    "accounting.statements": "Báo cáo tài chính",
    "accounting.assets": "Quản lý tài sản",
    "accounting.tax": "Quản lý thuế",
    "accounting.budget": "Quản lý ngân sách",
    "accounting.reports": "Báo cáo kế toán",

    employees: "Quản lý nhân viên",
    "employees.dashboard": "Bảng điều khiển nhân viên",
    "employees.leave": "Quản lý nghỉ phép",
    "employees.salary": "Quản lý lương",
    "employees.profile": "Hồ sơ nhân viên",
    "employees.attendance": "Quản lý chấm công",
    "employees.evaluation": "Đánh giá hiệu suất",
    "employees.communication": "Thông báo nội bộ",

    settings: "Cài đặt",
    "settings.dashboard": "Trung tâm cài đặt",
    "settings.accessControl": "Kiểm soát truy cập / Quản lý quyền",
    "settings.general": "Cài đặt chung",
    "settings.profile": "Cài đặt hồ sơ",
    "settings.notifications": "Cài đặt thông báo",
    "settings.integrations": "Cài đặt tích hợp",
    "settings.workflows": "Quản lý quy trình & mẫu",
    "settings.dataManagement": "Quản lý dữ liệu",
    "settings.auditLogs": "Nhật ký kiểm toán",
    "settings.billing": "Quản lý thanh toán & giấy phép",

    profile: "Hồ sơ",
    loading: "Đang tải...",
  },
  en: {
    // 앱 공통
    "app.title": "LN Partners Groupware",
    "app.redirecting": "Loading...",

    // 공통
    login: "Login",
    register: "Sign Up",
    logout: "Logout",
    dashboard: "Dashboard",
    customers: "Customers",
    "customers.list": "Customer List",
    "customers.add": "Add Customer",
    "customers.voc": "VOC Management",
    "customers.history": "Activity History",
    "customers.grades": "Grade Management",
    "customers.searchAndFilter": "Search & Filter",
    "customers.searchPlaceholder":
      "Search by company name, contact, industry...",
    "customers.allGrades": "All Grades",
    "customers.gradeA": "Grade A (VIP)",
    "customers.gradeB": "Grade B (Excellent)",
    "customers.gradeC": "Grade C (Regular)",
    "customers.addNew": "Add New Customer",
    "customers.total": "Total Customers",
    "customers.contact": "Contact",
    "customers.industry": "Industry",
    "customers.registeredDate": "Registered Date",
    "customers.viewDetails": "View Details",
    "customers.edit": "Edit",
    "customers.activityHistory": "Activity History",
    "customers.noResults": "No customers match the search criteria.",
    "customers.addFirst": "Register First Customer",
    "customers.add.description":
      "Register new customer information to expand your customer database",
    "customers.add.basicInfo.title": "Basic Information",
    "customers.add.basicInfo.description": "Enter customer basic information",
    "customers.add.companyName": "Company Name",
    "customers.add.companyName.placeholder": "Enter company name",
    "customers.add.contactName": "Contact Name",
    "customers.add.contactName.placeholder": "Enter contact name",
    "customers.add.email": "Email",
    "customers.add.email.placeholder": "Enter email address",
    "customers.add.phone": "Phone",
    "customers.add.phone.placeholder": "Enter phone number",
    "customers.add.industry": "Industry",
    "customers.add.industry.placeholder": "Enter industry",
    "customers.add.grade": "Customer Grade",
    "customers.add.address": "Address",
    "customers.add.address.placeholder": "Enter address",
    "customers.grade.A": "Grade A (VIP)",
    "customers.grade.B": "Grade B (Excellent)",
    "customers.grade.C": "Grade C (Regular)",
    "common.error": "An error occurred",

    // 글로벌 에러 메시지
    "globalError.title": "System Error",
    "globalError.description": "An unexpected error occurred. Please try again.",
    "globalError.retry": "Try Again",

    // 네비게이션
    "navigation.dashboard": "Dashboard",
    "navigation.customers": "Customers",
    "navigation.products": "Products",
    "navigation.marketing": "Marketing",
    "navigation.settings": "Settings",
    "navigation.sales": "Sales",
    "navigation.revenue": "Revenue",
    "navigation.accounting": "Accounting",
    "navigation.employees": "Employees",
    "navigation.profile": "Profile",

    // 사이드바
    "sidebar.companyName": "LN Partners",
    "sidebar.subTitle": "Groupware",
    "sidebar.menuTitle": "Menu",

    // 기타 필요한 번역들
    products: "Products",
    "products.list": "Product List",
    "products.add": "Add Product",
    "products.categories": "Category Management",
    "products.models": "Model Management",
    "products.competitors": "Competitor Information",
    "products.inventory": "Inventory Management",
    sales: "Sales Management",
    "sales.dashboard": "Sales Dashboard",
    "sales.opportunities": "Sales Opportunities",
    "sales.pipeline": "Sales Pipeline",
    "sales.quotes": "Quotes",
    "sales.activities": "Sales Activities",
    "sales.kpi": "Sales KPI",
    revenue: "Revenue Management",
    "revenue.dashboard": "Revenue Dashboard",
    "revenue.record": "Revenue Record",
    "revenue.quotes": "Quote Management",
    "revenue.orders": "Order Management",
    "revenue.payment": "Payment Management",
    "revenue.statistics": "Revenue Statistics",
    "revenue.goals": "Performance vs Goals",
    marketing: "Marketing",
    "marketing.dashboard": "Marketing Dashboard",
    "marketing.content": "Content Management",
    "marketing.monitoring": "Monitoring",
    "marketing.insights": "Insights",
    "marketing.abtest": "A/B Testing",
    "marketing.trends": "Trend Analysis",
    "marketing.engagement": "Engagement Management",
    "marketing.brandStrategy": "Brand Strategy",
    "marketing.marketAnalysis": "Market & Competitor Analysis",
    "marketing.planningProcess": "Marketing Planning & Process",
    "marketing.campaignCalendar": "Campaign Calendar",
    "marketing.contentLibrary": "Content Library",
    "marketing.influencerManagement": "Influencer Management",
    "marketing.budgetExpense": "Budget & Expense",
    "marketing.settings": "Settings",

    accounting: "Accounting Management",
    "accounting.dashboard": "Accounting Dashboard",
    "accounting.voucher": "Voucher Management",
    "accounting.ledger": "Ledger Management",
    "accounting.statements": "Financial Statements",
    "accounting.assets": "Asset Management",
    "accounting.tax": "Tax Management",
    "accounting.budget": "Budget Management",
    "accounting.reports": "Accounting Reports",

    employees: "Employee Management",
    "employees.dashboard": "Employee Dashboard",
    "employees.leave": "Leave Management",
    "employees.salary": "Salary Management",
    "employees.profile": "Employee Profile",
    "employees.attendance": "Attendance Management",
    "employees.evaluation": "Performance Evaluation",
    "employees.communication": "Internal Communication",

    settings: "Settings",
    "settings.dashboard": "Settings Center",
    "settings.accessControl": "Access Control / Permission Management",
    "settings.general": "General Settings",
    "settings.profile": "Profile Settings",
    "settings.notifications": "Notification Settings",
    "settings.integrations": "Integration Settings",
    "settings.workflows": "Workflow & Template Management",
    "settings.dataManagement": "Data Management",
    "settings.auditLogs": "Audit Logs",
    "settings.billing": "Billing & License Management",

    profile: "Profile",
    loading: "Loading...",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("ko");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") || "ko";
    setLanguage(savedLanguage);
  }, []);

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  const cycleLanguage = () => {
    const languages = ["ko", "en", "vi"];
    const currentIndex = languages.indexOf(language);
    const nextIndex = (currentIndex + 1) % languages.length;
    changeLanguage(languages[nextIndex]);
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, changeLanguage, cycleLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguageContext = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguageContext must be used within a LanguageProvider');
  }
  return context;
};