'use client'

import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  ko: {
    // 앱 공통
    'app.title': 'LN Partners 그룹웨어',
    'app.redirecting': '로딩 중입니다...',
    
    // 공통
    login: '로그인',
    register: '회원가입',
    logout: '로그아웃',
    dashboard: '대시보드',
    customers: '고객',
    'customers.list': '고객 목록',
    'customers.add': '고객 등록',
    'customers.voc': 'VOC 관리',
    'customers.history': '활동 이력',
    'customers.grades': '등급 관리',
    'customers.searchAndFilter': '검색 및 필터',
    'customers.searchPlaceholder': '회사명, 담당자, 업종으로 검색...',
    'customers.allGrades': '모든 등급',
    'customers.gradeA': 'A등급 (VIP)',
    'customers.gradeB': 'B등급 (우수)',
    'customers.gradeC': 'C등급 (일반)',
    'customers.addNew': '새 고객 등록',
    'customers.total': '전체 고객',
    'customers.contact': '담당자',
    'customers.industry': '업종',
    'customers.registeredDate': '등록일',
    'customers.viewDetails': '상세보기',
    'customers.edit': '수정',
    'customers.activityHistory': '활동이력',
    'customers.noResults': '검색 조건에 맞는 고객이 없습니다.',
    'customers.addFirst': '첫 번째 고객 등록하기',
    'customers.add.description': '새로운 고객 정보를 등록하여 고객 데이터베이스를 확장하세요',
    'customers.add.basicInfo.title': '기본 정보',
    'customers.add.basicInfo.description': '고객의 기본 정보를 입력하세요',
    'customers.add.companyName': '회사명',
    'customers.add.companyName.placeholder': '회사명을 입력하세요',
    'customers.add.contactName': '담당자명',
    'customers.add.contactName.placeholder': '담당자명을 입력하세요',
    'customers.add.email': '이메일',
    'customers.add.email.placeholder': '이메일 주소를 입력하세요',
    'customers.add.phone': '전화번호',
    'customers.add.phone.placeholder': '전화번호를 입력하세요',
    'customers.add.industry': '업종',
    'customers.add.industry.placeholder': '업종을 입력하세요',
    'customers.add.grade': '고객 등급',
    'customers.add.address': '주소',
    'customers.add.address.placeholder': '주소를 입력하세요',
    'customers.grade.A': 'A등급 (VIP)',
    'customers.grade.B': 'B등급 (우수)',
    'customers.grade.C': 'C등급 (일반)',
    'customers.add.companyType': '회사 유형',
    'customers.add.companyType.placeholder': '회사 유형을 선택하세요',
    'customers.add.companyType.customPlaceholder': '회사 유형을 입력하세요',
    'customers.add.grade.placeholder': '등급을 선택하세요',
    'customers.add.grade.customPlaceholder': '등급을 입력하세요',
    'customers.companyType.small': '중소기업',
    'customers.companyType.large': '대기업',
    'customers.companyType.startup': '스타트업',
    'customers.companyType.public': '공공기관',
    'customers.companyType.nonprofit': '비영리단체',
    'common.directInput': '직접 입력',
    'common.error': '오류가 발생했습니다',
    products: '제품',
    'products.list': '제품 목록',
    'products.add': '제품 등록',
    'products.categories': '카테고리 관리',
    'products.models': '모델 관리',
    'products.competitors': '경쟁사 정보',
    'products.inventory': '재고 관리',
    sales: '영업관리',
    'sales.dashboard': '영업 대시보드',
    'sales.opportunities': '영업기회',
    'sales.pipeline': '영업 파이프라인',
    'sales.quotes': '견적서',
    'sales.activities': '영업 활동',
    'sales.kpi': '영업 성과',
    revenue: '매출관리',
    'revenue.dashboard': '매출 대시보드',
    'revenue.record': '매출 기록',
    'revenue.quotes': '견적서 관리',
    'revenue.orders': '발주 관리',
    'revenue.payment': '입금 관리',
    'revenue.statistics': '매출 통계',
    'revenue.goals': '목표 대비 실적',
    marketing: '마케팅 관리',
    'marketing.dashboard': '마케팅 대시보드',
    'marketing.content': '콘텐츠 관리',
    'marketing.monitoring': '게시 모니터링',
    'marketing.insights': '성과분석',
    'marketing.abtest': 'A/B 테스트 관리',
    'marketing.trends': '시장 트렌드 분석',
    'marketing.engagement': '자동 응답 관리',
    'marketing.settings': '마케팅 설정',
    accounting: '회계 관리',
    'accounting.dashboard': '회계 대시보드',
    'accounting.voucher': '전표 관리',
    'accounting.ledger': '원장 관리',
    'accounting.statements': '재무제표',
    'accounting.assets': '자산 관리',
    'accounting.tax': '세무 관리',
    'accounting.budget': '예산 관리',
    'accounting.reports': '회계 보고서',
    'accounting.dashboard.description': '전체 회계 현황을 한눈에 확인하고 관리하세요',
    'accounting.totalRevenue': '총 매출',
    'accounting.totalExpenses': '총 비용',
    'accounting.netProfit': '순이익',
    'accounting.profitMargin': '이익률',
    'accounting.quickActions': '빠른 작업',
    'accounting.pendingTasks': '대기 중인 작업',
    'accounting.recentTransactions': '최근 거래 내역',
    'accounting.setup': '회계 설정',
    'accounting.setup.description': '베트남 회계기준에 맞는 기초 회계 정보를 설정하세요',
    'accounting.basicInfo': '기초 정보',
    'accounting.chartOfAccounts': '계정과목',
    'accounting.taxSettings': '세무 설정',
    'accounting.securitySettings': '보안 설정',
    'accounting.integrations': '외부 연동',
    'accounting.companyInfo': '회사 기본 정보',
    'accounting.companyName': '회사명',
    'accounting.taxCode': '세무코드',
    'accounting.address': '주소',
    'accounting.representative': '대표자명',
    'accounting.fiscalYear': '회계연도',
    'accounting.currency': '기본 통화',
    'accounting.save': '저장',
    'accounting.accountCode': '계정코드',
    'accounting.accountName': '계정명',
    'accounting.category': '분류',
    'accounting.status': '상태',
    'accounting.actions': '작업',
    'accounting.active': '활성',
    'accounting.inactive': '비활성',
    'accounting.edit': '수정',
    'accounting.vatSettings': 'VAT 설정',
    'accounting.taxType': '세금 유형',
    'accounting.addTaxType': '새 세금 유형 추가',
    'accounting.adminEmail': '관리자 이메일',
    'accounting.webhookToken': 'Webhook 검증 토큰',
    'accounting.twoFactorAuth': '2단계 인증 활성화',
    'accounting.ipWhitelist': 'IP 화이트리스트 사용',
    'accounting.saveSettings': '설정 저장',
    'accounting.externalSystems': '외부 시스템 연동',
    'accounting.apiKeyManagement': 'API 키 관리',
    'accounting.connected': '연결됨',
    'accounting.error': '오류',
    'accounting.disconnected': '연결 안됨',
    'accounting.lastSync': '마지막 동기화',
    'accounting.apiKey': 'API 키',
    'accounting.normal': '정상',

    // 영업 대시보드 
    'sales.dashboard.title': '영업 대시보드',
    'sales.dashboard.description': '영업 파이프라인과 성과 지표를 한눈에 확인하세요',
    'sales.totalOpportunities': '총 영업기회',
    'sales.active': '활성',
    'sales.conversionRate': '성공률',
    'sales.success': '성사',
    'sales.expectedRevenue': '예상 매출',
    'sales.totalPipelineValue': '총 파이프라인 가치',
    'sales.totalCustomers': '고객사 수',
    'sales.registeredCustomers': '등록된 고객사',
    'sales.pipeline': '영업 파이프라인',
    'sales.pipelineDistribution': '단계별 영업기회 분포',
    'sales.recentOpportunities': '최근 영업기회',
    'sales.newOpportunities': '새로 등록된 영업기회',
    'sales.noOpportunities': '등록된 영업기회가 없습니다.',
    'sales.quickActions': '빠른 액션',
    'sales.quickActionsDescription': '자주 사용하는 영업 기능들',
    'sales.newOpportunity': '새 영업기회',
    'sales.opportunityRegistration': '영업기회 등록',
    'sales.pipelineView': '파이프라인',
    'sales.pipelineStatus': '진행 현황 보기',
    'sales.performanceAnalysis': '성과 분석',
    'sales.kpiCheck': 'KPI 확인',
    'sales.stage.prospect': '잠재고객',
    'sales.stage.qualification': '자격심사', 
    'sales.stage.proposal': '제안',
    'sales.stage.negotiation': '협상',
    'sales.stage.closed_won': '성사',
    'sales.stage.closed_lost': '실패',
    'sales.previousMonth': '전월 대비',

    // 회계 대시보드 추가 번역
    'accounting.previousMonth': '전월 대비',
    'accounting.quickActionsDescription': '자주 사용하는 회계 기능에 빠르게 접근하세요',
    'accounting.pendingTasksDescription': '승인이나 처리가 필요한 항목들입니다',
    'accounting.recentTransactionsDescription': '최근 회계 거래들을 확인하세요',
    'accounting.pendingVouchers': '대기 중인 전표',
    'accounting.pendingApproval': '승인 대기',
    'accounting.overduePayments': '연체된 결제',

    // 고객사 관련 번역
    'customer.add.title': '새로운 고객사 추가',
    'customer.add.description': '고객사 정보와 담당자 정보를 입력해 주세요',
    'customer.createSuccess': '고객사가 성공적으로 등록되었습니다.',
    'customer.createError': '고객사 등록 중 오류가 발생했습니다.',
    'customer.grade': '고객 등급',
    'customer.gradeSelect': '고객 등급 선택',
    'customer.gradeCustomPlaceholder': '고객 등급을 입력하세요',
    'customer.grade.vip': 'A급 (VIP)',
    'customer.grade.excellent': 'B급 (우수)',
    'customer.grade.normal': 'C급 (일반)',
    'customer.grade.custom': '직접입력',

    // 회사 정보 관련 번역
    'company.info.basic': '기본 회사 정보',
    'company.info.description': '고객사의 기본적인 정보를 입력해 주세요',
    'company.name': '회사명',
    'company.namePlaceholder': '회사명을 입력하세요',
    'company.industry': '업종',
    'company.industryPlaceholder': '업종을 입력하세요',
    'company.type': '회사 유형',
    'company.typeSelect': '회사 유형 선택',
    'company.typeCustomPlaceholder': '회사 유형을 입력하세요',
    'company.type.small': '중소기업',
    'company.type.large': '대기업',
    'company.type.startup': '스타트업',
    'company.type.public': '공공기관',
    'company.type.nonprofit': '비영리단체',
    'company.type.custom': '직접입력',

    // 주소 관련 번역
    'address.title': '주소',
    'address.selectProvince': '도/시 선택',
    'address.selectDistrict': '구/군 선택',
    'address.selectWard': '동/읍/면 선택',
    'address.detailAddress': '상세 주소를 입력하세요',

    // 영업사원 관련 번역
    'sales.person.assigned': '담당 영업사원',
    'sales.person.description': '이 고객사를 담당할 영업사원을 선택해 주세요',
    'sales.person.placeholder': '담당 영업사원을 검색하여 선택하세요',

    // 이미지 관련 번역
    'image.registration': '이미지 등록',
    'image.description': '고객사의 프로필 이미지와 시설 사진을 등록해 주세요',
    'image.profile': '고객사 프로필 이미지',
    'image.facility': '시설 사진',
    'image.add': '이미지 추가',

    // 담당자 관련 번역
    'contact.info': '담당자 정보',
    'contact.description': '고객사의 담당자들을 추가해 주세요',
    'contact.person': '담당자',
    'contact.add': '담당자 추가',
    'contact.profileImage': '프로필 이미지',
    'contact.name': '이름',
    'contact.namePlaceholder': '담당자 이름',
    'contact.department': '부서',
    'contact.departmentPlaceholder': '부서명',
    'contact.position': '직책',
    'contact.positionPlaceholder': '직책',
    'contact.phone': '전화번호',
    'contact.phonePlaceholder': '전화번호',
    'contact.email': '이메일',
    'contact.emailPlaceholder': '이메일',
    'contact.birthDate': '생년월일',

    // 검색 관련 번역
    'search.salesPerson': '담당자 검색...',

    // 버튼 관련 번역
    'button.cancel': '취소',
    'button.register': '고객사 등록',
    'button.submitting': '등록 중...',

    // 공통 번역
    'loading': '로딩 중...',

    employees: '직원 관리',
    'employees.dashboard': '직원 대시보드',
    'employees.leave': '휴가 관리',
    'employees.salary': '급여 관리',
    'employees.profile': '직원 프로필',
    'employees.attendance': '근태 관리',
    'employees.evaluation': '성과 평가',
    'employees.communication': '공지사항',

    settings: '설정',
    profile: '프로필',

    // 로그인 페이지
    'login.title': '로그인',
    'login.description': '계정에 로그인하여 CRM 시스템을 이용하세요.',
    'login.email': '이메일',
    'login.password': '비밀번호',
    'login.submit': '로그인',
    'login.register.link': '계정이 없으신가요? 회원가입',
    'login.success': '로그인 성공',
    'login.success.description': '대시보드로 이동합니다.',
    'login.error': '로그인 실패',
    'login.error.description': '이메일과 비밀번호를 확인해주세요.',
    'login.loading': '로그인 중...',

    // 회원가입 페이지
    'register.title': '회원가입',
    'register.description': '새 계정을 만들어 CRM 시스템을 시작하세요.',
    'register.name': '이름',
    'register.name.placeholder': '예: 김철수',
    'register.email': '이메일',
    'register.password': '비밀번호',
    'register.confirmPassword': '비밀번호 확인',
    'register.department': '부서',
    'register.department.sales': '영업',
    'register.department.inventory': '재고/배송',
    'register.department.marketing': '마케팅',
    'register.department.accounting': '회계',
    'register.department.support': '고객지원',
    'register.department.other': '기타',
    'register.department.otherInput': '기타 부서명을 입력하세요',
    'register.position': '직책',
    'register.employeeId': '임사번호',
    'register.joinDate': '입사일',
    'register.phoneNumber': '전화번호',
    'register.address': '주소',
    'register.address.placeholder': '예: 서울특별시 강남구 테헤란로 123',
    'register.nationality': '국적',
    'register.nationality.vietnam': '베트남',
    'register.nationality.korea': '한국',
    'register.nationality.usa': '미국',
    'register.nationality.japan': '일본',
    'register.nationality.china': '중국',
    'register.nationality.thailand': '태국',
    'register.nationality.other': '기타',
    'register.birthDate': '생년월일',
    'register.visaStatus': '비자연한자',
    'register.visaStatus.optional': '선택(해당하는 경우만 입력)',
    'register.emergencyContact': '비상연락처',
    'register.emergencyContact.name': '이름',
    'register.emergencyContact.relationship': '관계',
    'register.emergencyContact.phone': '전화번호',
    'register.skills': '보유기술',
    'register.skills.placeholder': '예: React, Next.js, Node.js, Photoshop, sales 등',
    'register.experience': '경력',
    'register.experience.company': '회사명',
    'register.experience.position': '직책',
    'register.experience.startDate': '시작일',
    'register.experience.endDate': '종료일',
    'register.experience.description': '설명',
    'register.submit': '회원가입',
    'register.login.link': '이미 계정이 있으신가요? 로그인',
    'register.addEmergencyContact': '비상연락처 추가',
    'register.addExperience': '경력 추가',
    'register.addSkill': '기술 추가',
    'register.required': '필수',
    'register.optional': '선택사항',

    // 공통 텍스트
    'common.success': '성공',
    'common.error': '오류',
    'common.cancel': '취소',
    'common.edit': '수정',
    'common.save': '저장',
    'common.add': '추가',
    'common.select': '선택',
    'common.notSet': '설정되지 않음',
    'common.noData': '데이터 없음',

    // 프로필 관리
    'profile.title': '프로필 관리',
    'profile.description': '개인정보 및 업무정보를 관리하세요',
    'profile.basicInfo': '기본 정보',
    'profile.personalInfo': '개인 정보',
    'profile.workInfo': '업무 정보',
    'profile.updateSuccess': '프로필이 성공적으로 업데이트되었습니다.',
    'profile.updateError': '프로필 업데이트 중 오류가 발생했습니다.',
    'profile.fetchError': '프로필 정보를 불러오는 중 오류가 발생했습니다.',

    // 비밀번호 강도 및 유효성 검사
    'register.password.strength': '비밀번호 강도',
    'register.password.strength.weak': '약함',
    'register.password.strength.medium': '중간',
    'register.password.strength.strong': '강함',
    'register.password.requirement.minLength': '최소 8자 이상',
    'register.password.requirement.uppercase': '대문자 1개 이상 포함',
    'register.password.requirement.specialChar': '특수문자 1개 이상 포함',
    'register.password.requirement.match': '비밀번호 일치',
    'register.email.invalid': '유효하지 않은 이메일 형식입니다',
    'register.phone.country': '국가',
    'register.phone.selectCountry': '국가를 선택하세요',
    'register.phone.invalid': '유효하지 않은 전화번호입니다',

    // 대시보드
    'dashboard.title': '대시보드',
    'dashboard.description': '전체 비즈니스 현황을 한눈에 확인하세요.',
    'dashboard.totalCustomers': '총 고객',
    'dashboard.activeOpportunities': '활성 영업기회',
    'dashboard.monthlyRevenue': '월간 매출',
    'dashboard.successRate': '성공률',
    'dashboard.recentCustomers': '최근 고객',
    'dashboard.recentCustomers.description': '최근에 등록된 고객 목록입니다.',
    'dashboard.opportunities': '진행 중인 영업기회',
    'dashboard.opportunities.description': '현재 진행 중인 주요 영업기회입니다.',

    // app/page.js
 'sidebar.companyName': 'LN Partners',
 'sidebar.subTitle': '그룹웨어',
 'sidebar.menuTitle': '메뉴',
    'app.title': 'CRM 시스템',
    'app.redirecting': '로그인 페이지로 이동 중...',

    // common
    'previousMonth': '전월 대비',

    // 고객 관련 번역
    'customers.title': '고객 관리',
    'customers.description': '고객 정보를 효율적으로 관리하고 분석하세요',
    'customers.addNew': '새 고객 추가',
    'customers.total': '전체 고객',
    'customers.gradeA': 'A급 고객',
    'customers.gradeB': 'B급 고객',
    'customers.gradeC': 'C급 고객',
    'customers.allGrades': '모든 등급',
    'customers.searchPlaceholder': '고객명 또는 담당자명으로 검색...',

    // 고객 상세페이지 번역
    'customer.basicInfo': '기본 회사 정보',
    'customer.basicInfoDescription': '고객사의 기본적인 정보를 확인하고 수정할 수 있습니다',
    'customer.companyInfo': '회사 정보',
    'customer.companyInfoDescription': '고객사의 기본 정보',
    'customer.name': '회사명',
    'customer.assignedUser': '담당자',
    'customer.manager': '담당자',
    'customer.industry': '업종',
    'customer.businessType': '업종',
    'customer.companyType': '회사 유형',
    'customer.organizationType': '조직 유형',
    'customer.grade': '고객 등급',
    'customer.address': '주소',
    'customer.email': '이메일',
    'customer.phone': '전화번호',
    'customer.contactInfo': '연락처 정보',
    'customer.contactInfoDescription': '고객사의 연락처 정보를 관리합니다',
    'customer.imageGallery': '이미지 갤러리',
    'customer.imageGalleryDescription': '고객사의 프로필 이미지와 시설 사진을 확인하고 관리할 수 있습니다',
    'customer.contactPersons': '담당자 정보',
    'customer.contactPersonsDescription': '고객사의 담당자들의 상세 정보를 관리합니다',
    'customer.addContactPerson': '담당자 추가',
    'customer.summary': '요약 정보',
    'customer.summaryInfo': '요약 정보',
    'customer.quickActions': '빠른 액션',
    'customer.createdAt': '등록일',
    'customer.updatedAt': '마지막 수정',
    'customer.selectAssignedUser': '담당자를 선택하세요',

    // 회사 유형 번역
    'customer.companyType.sme': '중소기업',
    'customer.companyType.large': '대기업',
    'customer.companyType.startup': '스타트업',
    'customer.companyType.public': '공공기관',
    'customer.companyType.nonprofit': '비영리단체',

    // 고객 등급 번역
    'customer.grade.a': 'A급 (VIP)',
    'customer.grade.b': 'B급 (우수)',
    'customer.grade.c': 'C급 (일반)',
    'customer.grade.d': 'D급 (표준)',
    'customer.grade.e': 'E급 (기본)',

    // 회사명 중복 검사 관련
    'customer.name.duplicate': '이미 존재하는 회사명입니다',
    'customer.name.available': '사용 가능한 회사명입니다',
    'customer.name.checkError': '회사명 중복 검사 중 오류가 발생했습니다',
  },
  vi: {
    // 앱 공통
    'app.title': 'LN Partners Groupware',
    'app.redirecting': 'Đang tải...',
    
    // 공통
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    dashboard: 'Bảng điều khiển',
    customers: 'Khách hàng',
    'customers.list': 'Danh sách khách hàng', // Corrected
    'customers.add': 'Thêm khách hàng', // Corrected
    'customers.voc': 'Quản lý phản hồi khách hàng (VOC)', // Corrected
    'customers.history': 'Lịch sử hoạt động khách hàng', // Corrected
    'customers.grades': 'Quản lý cấp độ khách hàng', // Corrected
    'customers.searchAndFilter': 'Tìm kiếm & Lọc',
    'customers.searchPlaceholder': 'Tìm kiếm theo tên công ty, người liên hệ, ngành nghề...',
    'customers.allGrades': 'Tất cả cấp độ',
    'customers.gradeA': 'Cấp A (VIP)',
    'customers.gradeB': 'Cấp B (Xuất sắc)',
    'customers.gradeC': 'Cấp C (Thường)',
    'customers.addNew': 'Thêm khách hàng mới',
    'customers.total': 'Tổng khách hàng',
    'customers.contact': 'Người liên hệ',
    'customers.industry': 'Ngành nghề',
    'customers.registeredDate': 'Ngày đăng ký',
    'customers.viewDetails': 'Xem chi tiết',
    'customers.edit': 'Chỉnh sửa',
    'customers.activityHistory': 'Lịch sử hoạt động',
    'customers.noResults': 'Không có khách hàng nào phù hợp với tiêu chí tìm kiếm.',
    'customers.addFirst': 'Đăng ký khách hàng đầu tiên',
    'customers.add.description': 'Đăng ký thông tin khách hàng mới để mở rộng cơ sở dữ liệu khách hàng',
    'customers.add.basicInfo.title': 'Thông tin cơ bản',
    'customers.add.basicInfo.description': 'Nhập thông tin cơ bản của khách hàng',
    'customers.add.companyName': 'Tên công ty',
    'customers.add.companyName.placeholder': 'Nhập tên công ty',
    'customers.add.contactName': 'Tên người liên hệ',
    'customers.add.contactName.placeholder': 'Nhập tên người liên hệ',
    'customers.add.email': 'Email',
    'customers.add.email.placeholder': 'Nhập địa chỉ email',
    'customers.add.phone': 'Số điện thoại',
    'customers.add.phone.placeholder': 'Nhập số điện thoại',
    'customers.add.industry': 'Ngành nghề',
    'customers.add.industry.placeholder': 'Nhập ngành nghề',
    'customers.add.grade': 'Cấp độ khách hàng',
    'customers.add.address': 'Địa chỉ',
    'customers.add.address.placeholder': 'Nhập địa chỉ',
    'customers.grade.A': 'Hạng A (VIP)',
    'customers.grade.B': 'Hạng B (Tốt)',
    'customers.grade.C': 'Hạng C (Thường)',
    'customers.add.companyType': 'Loại công ty',
    'customers.add.companyType.placeholder': 'Chọn loại công ty',
    'customers.add.companyType.customPlaceholder': 'Nhập loại công ty',
    'customers.add.grade.placeholder': 'Chọn hạng khách hàng',
    'customers.add.grade.customPlaceholder': 'Nhập hạng khách hàng',
    'customers.companyType.small': 'Doanh nghiệp nhỏ',
    'customers.companyType.large': 'Tập đoàn lớn',
    'customers.companyType.startup': 'Công ty khởi nghiệp',
    'customers.companyType.public': 'Cơ quan công',
    'customers.companyType.nonprofit': 'Tổ chức phi lợi nhuận',
    'common.directInput': 'Nhập trực tiếp',
    'common.error': 'Đã xảy ra lỗi',
    products: 'Sản phẩm',
    'products.list': 'Danh sách sản phẩm',
    'products.add': 'Đăng ký sản phẩm',
    'products.categories': 'Quản lý danh mục',
    'products.models': 'Quản lý mô hình',
    'products.competitors': 'Thông tin đối thủ',
    'products.inventory': 'Quản lý kho',
    sales: 'Quản lý bán hàng',
    'sales.dashboard': 'Bảng điều khiển bán hàng',
    'sales.opportunities': 'Cơ hội bán hàng',
    'sales.pipeline': 'Quy trình bán hàng',
    'sales.quotes': 'Báo giá',
    'sales.activities': 'Hoạt động bán hàng',
    'sales.kpi': 'Hiệu suất bán hàng',
    revenue: 'Quản lý doanh thu',
    'revenue.dashboard': 'Bảng điều khiển doanh thu',
    'revenue.record': 'Ghi nhận doanh thu',
    'revenue.quotes': 'Quản lý báo giá',
    'revenue.orders': 'Quản lý đơn hàng',
    'revenue.payment': 'Quản lý thanh toán',
    'revenue.statistics': 'Thống kê doanh thu',
    'revenue.goals': 'Thành tích so với mục tiêu',
    marketing: 'Quản lý tiếp thị',
    'marketing.dashboard': 'Bảng điều khiển tiếp thị',
    'marketing.content': 'Quản lý nội dung',
    'marketing.monitoring': 'Giám sát đăng bài',
    'marketing.insights': 'Phân tích hiệu suất',
    'marketing.abtest': 'Quản lý A/B Test',
    'marketing.trends': 'Phân tích xu hướng thị trường',
    'marketing.engagement': 'Quản lý phản hồi tự động',
    'marketing.settings': 'Cài đặt tiếp thị',
    accounting: 'Quản lý kế toán',
    'accounting.dashboard': 'Bảng điều khiển kế toán',
    'accounting.voucher': 'Quản lý chứng từ',
    'accounting.ledger': 'Quản lý sổ cái',
    'accounting.statements': 'Báo cáo tài chính',
    'accounting.assets': 'Quản lý tài sản',
    'accounting.tax': 'Quản lý thuế',
    'accounting.budget': 'Quản lý ngân sách',
    'accounting.reports': 'Báo cáo kế toán',
    'accounting.dashboard.description': 'Xem tổng quan tình hình kế toán trong một cái nhìn',
    'accounting.totalRevenue': 'Tổng doanh thu',
    'accounting.totalExpenses': 'Tổng chi phí',
    'accounting.netProfit': 'Lợi nhuận ròng',
    'accounting.profitMargin': 'Tỷ lệ lợi nhuận',
    'accounting.quickActions': 'Hành động nhanh',
    'accounting.pendingTasks': 'Công việc đang chờ',
    'accounting.recentTransactions': 'Giao dịch gần đây',
    'accounting.setup': 'Thiết lập kế toán',
    'accounting.setup.description': 'Thiết lập thông tin kế toán cơ bản theo chuẩn kế toán Việt Nam',
    'accounting.basicInfo': 'Thông tin cơ bản',
    'accounting.chartOfAccounts': 'Tài khoản kế toán',
    'accounting.taxSettings': 'Thiết lập thuế',
    'accounting.securitySettings': 'Thiết lập bảo mật',
    'accounting.integrations': 'Tích hợp bên ngoài',
    'accounting.companyInfo': 'Thông tin công ty',
    'accounting.companyName': 'Tên công ty',
    'accounting.taxCode': 'Mã số thuế',
    'accounting.address': 'Địa chỉ',
    'accounting.representative': 'Người đại diện',
    'accounting.fiscalYear': 'Năm tài chính',
    'accounting.currency': 'Đơn vị tiền tệ',
    'accounting.save': 'Lưu',
    'accounting.accountCode': 'Mã tài khoản',
    'accounting.accountName': 'Tên tài khoản',
    'accounting.category': 'Phân loại',
    'accounting.status': 'Trạng thái',
    'accounting.actions': 'Hành động',
    'accounting.active': 'Hoạt động',
    'accounting.inactive': 'Không hoạt động',
    'accounting.edit': 'Chỉnh sửa',
    'accounting.vatSettings': 'Thiết lập VAT',
    'accounting.taxType': 'Loại thuế',
    'accounting.addTaxType': 'Thêm loại thuế mới',
    'accounting.adminEmail': 'Email quản trị',
    'accounting.webhookToken': 'Token xác thực Webhook',
    'accounting.twoFactorAuth': 'Kích hoạt xác thực 2 bước',
    'accounting.ipWhitelist': 'Sử dụng danh sách IP trắng',
    'accounting.saveSettings': 'Lưu thiết lập',
    'accounting.externalSystems': 'Tích hợp hệ thống bên ngoài',
    'accounting.apiKeyManagement': 'Quản lý API Key',
    'accounting.connected': 'Đã kết nối',
    'accounting.error': 'Lỗi',
    'accounting.disconnected': 'Chưa kết nối',
    'accounting.lastSync': 'Đồng bộ lần cuối',
    'accounting.apiKey': 'API Key',
    'accounting.normal': 'Bình thường',

    // 영업 대시보드
    'sales.dashboard.title': 'Bảng điều khiển bán hàng',
    'sales.dashboard.description': 'Kiểm tra quy trình bán hàng và các chỉ số hiệu suất trong một cái nhìn',
    'sales.totalOpportunities': 'Tổng cơ hội bán hàng',
    'sales.active': 'Hoạt động',
    'sales.conversionRate': 'Tỷ lệ thành công',
    'sales.success': 'Thành công',
    'sales.expectedRevenue': 'Doanh thu dự kiến',
    'sales.totalPipelineValue': 'Tổng giá trị quy trình',
    'sales.totalCustomers': 'Số lượng khách hàng',
    'sales.registeredCustomers': 'Khách hàng đã đăng ký',
    'sales.pipeline': 'Quy trình bán hàng',
    'sales.pipelineDistribution': 'Phân bổ cơ hội theo giai đoạn',
    'sales.recentOpportunities': 'Cơ hội gần đây',
    'sales.newOpportunities': 'Cơ hội mới đăng ký',
    'sales.noOpportunities': 'Không có cơ hội bán hàng nào được đăng ký.',
    'sales.quickActions': 'Hành động nhanh',
    'sales.quickActionsDescription': 'Truy cập nhanh các tính năng bán hàng thường dùng',
    'sales.newOpportunity': 'Cơ hội mới',
    'sales.opportunityRegistration': 'Đăng ký cơ hội',
    'sales.pipelineView': 'Quy trình',
    'sales.pipelineStatus': 'Xem trạng thái tiến độ',
    'sales.performanceAnalysis': 'Phân tích hiệu suất',
    'sales.kpiCheck': 'Kiểm tra KPI',
    'sales.stage.prospect': 'Khách hàng tiềm năng',
    'sales.stage.qualification': 'Đánh giá',
    'sales.stage.proposal': 'Đề xuất',
    'sales.stage.negotiation': 'Đàm phán',
    'sales.stage.closed_won': 'Thành công',
    'sales.stage.closed_lost': 'Thất bại',
    'sales.previousMonth': 'So với tháng trước',

    // 회계 대시보드 추가 번역
    'accounting.previousMonth': 'So với tháng trước',
    'accounting.quickActionsDescription': 'Truy cập nhanh các tính năng kế toán thường dùng',
    'accounting.pendingTasksDescription': 'Các mục cần phê duyệt hoặc xử lý',
    'accounting.recentTransactionsDescription': 'Kiểm tra các giao dịch kế toán gần đây',
    'accounting.pendingVouchers': 'Chứng từ chờ xử lý',
    'accounting.pendingApproval': 'Chờ phê duyệt',
    'accounting.overduePayments': 'Thanh toán quá hạn',

    // 고객사 관련 번역
    'customer.add.title': 'Thêm khách hàng mới',
    'customer.add.description': 'Nhập thông tin khách hàng và người liên hệ',
    'customer.createSuccess': 'Khách hàng đã được đăng ký thành công.',
    'customer.createError': 'Có lỗi xảy ra khi đăng ký khách hàng.',
    'customer.grade': 'Cấp độ khách hàng',
    'customer.gradeSelect': 'Chọn cấp độ khách hàng',
    'customer.gradeCustomPlaceholder': 'Nhập cấp độ khách hàng',
    'customer.grade.vip': 'Cấp A (VIP)',
    'customer.grade.excellent': 'Cấp B (Xuất sắc)',
    'customer.grade.normal': 'Cấp C (Thông thường)',
    'customer.grade.custom': 'Nhập trực tiếp',

    // 회사 정보 관련 번역
    'company.info.basic': 'Thông tin công ty cơ bản',
    'company.info.description': 'Nhập thông tin cơ bản của khách hàng',
    'company.name': 'Tên công ty',
    'company.namePlaceholder': 'Nhập tên công ty',
    'company.industry': 'Ngành nghề',
    'company.industryPlaceholder': 'Nhập ngành nghề',
    'company.type': 'Loại công ty',
    'company.typeSelect': 'Chọn loại công ty',
    'company.typeCustomPlaceholder': 'Nhập loại công ty',
    'company.type.small': 'Doanh nghiệp nhỏ',
    'company.type.large': 'Tập đoàn lớn',
    'company.type.startup': 'Công ty khởi nghiệp',
    'company.type.public': 'Cơ quan công',
    'company.type.nonprofit': 'Tổ chức phi lợi nhuận',
    'company.type.custom': 'Nhập trực tiếp',

    // 주소 관련 번역
    'address.title': 'Địa chỉ',
    'address.selectProvince': 'Chọn tỉnh/thành phố',
    'address.selectDistrict': 'Chọn quận/huyện',
    'address.selectWard': 'Chọn phường/xã',
    'address.detailAddress': 'Nhập địa chỉ chi tiết',

    // 영업사원 관련 번역
    'sales.person.assigned': 'Nhân viên kinh doanh phụ trách',
    'sales.person.description': 'Chọn nhân viên kinh doanh phụ trách khách hàng này',
    'sales.person.placeholder': 'Tìm kiếm và chọn nhân viên kinh doanh',

    // 이미지 관련 번역
    'image.registration': 'Đăng ký hình ảnh',
    'image.description': 'Đăng ký ảnh đại diện và ảnh cơ sở vật chất của khách hàng',
    'image.profile': 'Ảnh đại diện khách hàng',
    'image.facility': 'Ảnh cơ sở vật chất',
    'image.add': 'Thêm ảnh',

    // 담당자 관련 번역
    'contact.info': 'Thông tin người liên hệ',
    'contact.description': 'Thêm người liên hệ của khách hàng',
    'contact.person': 'Người liên hệ',
    'contact.add': 'Thêm người liên hệ',
    'contact.profileImage': 'Ảnh đại diện',
    'contact.name': 'Tên',
    'contact.namePlaceholder': 'Tên người liên hệ',
    'contact.department': 'Phòng ban',
    'contact.departmentPlaceholder': 'Tên phòng ban',
    'contact.position': 'Chức vụ',
    'contact.positionPlaceholder': 'Chức vụ',
    'contact.phone': 'Số điện thoại',
    'contact.phonePlaceholder': 'Số điện thoại',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Email',
    'contact.birthDate': 'Ngày sinh',

    // 검색 관련 번역
    'search.salesPerson': 'Tìm kiếm người liên hệ...',

    // 버튼 관련 번역
    'button.cancel': 'Hủy',
    'button.register': 'Đăng ký khách hàng',
    'button.submitting': 'Đang đăng ký...',

    // 공통 번역
    'loading': 'Đang tải...',

    employees: 'Quản lý nhân viên',
    'employees.dashboard': 'Bảng điều khiển nhân viên',
    'employees.leave': 'Quản lý nghỉ phép',
    'employees.salary': 'Quản lý lương',
    'employees.profile': 'Hồ sơ nhân viên',
    'employees.attendance': 'Quản lý chấm công',
    'employees.evaluation': 'Đánh giá hiệu suất',
    'employees.communication': 'Thông báo nội bộ',

    settings: 'Cài đặt',
    profile: 'Hồ sơ',

    // 로그인 페이지
    'login.title': 'Đăng nhập',
    'login.description': 'Đăng nhập vào tài khoản của bạn để sử dụng hệ thống CRM.',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.submit': 'Đăng nhập',
    'login.register.link': 'Chưa có tài khoản? Đăng ký',
    'login.success': 'Đăng nhập thành công',
    'login.success.description': 'Chuyển đến bảng điều khiển.',
    'login.error': 'Đăng nhập thất bại',
    'login.error.description': 'Vui lòng kiểm tra email và mật khẩu.',
    'login.loading': 'Đang đăng nhập...',

    // 회원가입 페이지
    'register.title': 'Đăng ký',
    'register.description': 'Tạo tài khoản mới để bắt đầu với hệ thống CRM.',
    'register.name': 'Họ và Tên',
    'register.name.placeholder': 'Ví dụ: Dư Quang Phong',
    'register.email': 'Email',
    'register.password': 'Mật khẩu',
    'register.confirmPassword': 'Xác nhận mật khẩu',
    'register.department': 'Phòng ban',
    'register.department.sales': 'Kinh doanh',
    'register.department.inventory': 'Kho/Vận chuyển',
    'register.department.marketing': 'Marketing',
    'register.department.accounting': 'Kế toán',
    'register.department.support': 'Hỗ trợ khách hàng',
    'register.department.other': 'Khác',
    'register.department.otherInput': 'Nhập tên phòng ban khác',
    'register.position': 'Chức vụ',
    'register.employeeId': 'Mã nhân viên',
    'register.joinDate': 'Ngày vào làm',
    'register.phoneNumber': 'Số điện thoại',
    'register.address': 'Địa chỉ',
    'register.address.placeholder': 'Ví dụ: 118 Huỳnh Tấn Phát, Tân Thuận Tây, Quận 7, Hồ Chí Minh',
    'register.nationality': 'Quốc tịch',
    'register.nationality.vietnam': 'Việt Nam',
    'register.nationality.korea': 'Hàn Quốc',
    'register.nationality.usa': 'Hoa Kỳ',
    'register.nationality.japan': 'Nhật Bản',
    'register.nationality.china': 'Trung Quốc',
    'register.nationality.thailand': 'Thái Lan',
    'register.nationality.other': 'Khác',
    'register.birthDate': 'Ngày sinh',
    'register.visaStatus': 'Tình trạng visa',
    'register.visaStatus.optional': 'Tùy chọn (chỉ nhập nếu áp dụng)',
    'register.emergencyContact': 'Liên hệ khẩn cấp',
    'register.emergencyContact.name': 'Tên',
    'register.emergencyContact.relationship': 'Mối quan hệ',
    'register.emergencyContact.phone': 'Số điện thoại',
    'register.skills': 'Kỹ năng',
    'register.skills.placeholder': 'Ví dụ: React, Next.js, Node.js, Photoshop, sales, v.v',
    'register.experience': 'Kinh nghiệm',
    'register.experience.company': 'Công ty',
    'register.experience.position': 'Chức vụ',
    'register.experience.startDate': 'Ngày bắt đầu',
    'register.experience.endDate': 'Ngày kết thúc',
    'register.experience.description': 'Mô tả',
    'register.submit': 'Đăng ký',
    'register.login.link': 'Đã có tài khoản? Đăng nhập',
    'register.addEmergencyContact': 'Thêm liên hệ khẩn cấp',
    'register.addExperience': 'Thêm kinh nghiệm',
    'register.addSkill': 'Thêm kỹ năng',
    'register.required': 'Bắt buộc',
    'register.optional': 'Tùy chọn',

    // 공통 텍스트
    'common.success': 'Thành công',
    'common.error': 'Lỗi',
    'common.cancel': 'Hủy',
    'common.edit': 'Chỉnh sửa',
    'common.save': 'Lưu',
    'common.add': 'Thêm',
    'common.select': 'Chọn',
    'common.notSet': 'Chưa thiết lập',
    'common.noData': 'Không có dữ liệu',

    // 프로필 관리
    'profile.title': 'Quản lý hồ sơ',
    'profile.description': 'Quản lý thông tin cá nhân và công việc của bạn',
    'profile.basicInfo': 'Thông tin cơ bản',
    'profile.personalInfo': 'Thông tin cá nhân',
    'profile.workInfo': 'Thông tin công việc',
    'profile.updateSuccess': 'Hồ sơ đã được cập nhật thành công.',
    'profile.updateError': 'Đã xảy ra lỗi khi cập nhật hồ sơ.',
    'profile.fetchError': 'Đã xảy ra lỗi khi tải thông tin hồ sơ.',

    // 비밀번호 강도 및 유효성 검사
    'register.password.strength': 'Độ mạnh mật khẩu',
    'register.password.strength.weak': 'Yếu',
    'register.password.strength.medium': 'Trung bình',
    'register.password.strength.strong': 'Mạnh',
    'register.password.requirement.minLength': 'Tối thiểu 8 ký tự',
    'register.password.requirement.uppercase': 'Ít nhất 1 chữ hoa',
    'register.password.requirement.specialChar': 'Ít nhất 1 ký tự đặc biệt',
    'register.password.requirement.match': 'Mật khẩu khớp',
    'register.email.invalid': 'Định dạng email không hợp lệ',
    'register.phone.country': 'Quốc gia',
    'register.phone.selectCountry': 'Chọn quốc gia',
    'register.phone.invalid': 'Số điện thoại không hợp lệ',

    // 대시보드
    'dashboard.title': 'Bảng điều khiển',
    'dashboard.description': 'Xem tổng quan tình hình kinh doanh trong một cái nhìn.',
    'dashboard.totalCustomers': 'Tổng khách hàng',
    'dashboard.activeOpportunities': 'Cơ hội đang hoạt động',
    'dashboard.monthlyRevenue': 'Doanh thu hàng tháng',
    'dashboard.successRate': 'Tỷ lệ thành công',
    'dashboard.recentCustomers': 'Khách hàng gần đây',
    'dashboard.recentCustomers.description': 'Danh sách khách hàng đăng ký gần đây.',
    'dashboard.opportunities': 'Cơ hội đang tiến hành',
    'dashboard.opportunities.description': 'Các cơ hội bán hàng chính đang tiến hành.',

    // app/page.js
 'sidebar.companyName': 'LN Partners',
 'sidebar.subTitle': 'Groupware',
 'sidebar.menuTitle': 'Menu',
    'app.title': 'Hệ thống CRM',
    'app.redirecting': 'Đang chuyển hướng đến trang đăng nhập...',

    // common
    'previousMonth': 'So với tháng trước',

    // 고객 관련 번역
    'customers.title': 'Quản lý khách hàng',
    'customers.description': 'Quản lý và phân tích thông tin khách hàng hiệu quả',
    'customers.addNew': 'Thêm khách hàng mới',
    'customers.total': 'Tổng khách hàng',
    'customers.gradeA': 'Khách hàng hạng A',
    'customers.gradeB': 'Khách hàng hạng B',
    'customers.gradeC': 'Khách hàng hạng C',
    'customers.allGrades': 'Tất cả hạng',
    'customers.searchPlaceholder': 'Tìm kiếm theo tên công ty hoặc người phụ trách...',

    // 고객 상세페이지 번역
    'customer.basicInfo': 'Thông tin công ty cơ bản',
    'customer.basicInfoDescription': 'Xem và chỉnh sửa thông tin cơ bản của khách hàng',
    'customer.companyInfo': 'Thông tin công ty',
    'customer.companyInfoDescription': 'Thông tin cơ bản của công ty',
    'customer.name': 'Tên công ty',
    'customer.assignedUser': 'Người phụ trách',
    'customer.manager': 'Người quản lý',
    'customer.industry': 'Ngành nghề',
    'customer.businessType': 'Loại hình kinh doanh',
    'customer.companyType': 'Loại công ty',
    'customer.organizationType': 'Loại tổ chức',
    'customer.grade': 'Hạng khách hàng',
    'customer.address': 'Địa chỉ',
    'customer.email': 'Email',
    'customer.phone': 'Số điện thoại',
    'customer.contactInfo': 'Thông tin liên hệ',
    'customer.contactInfoDescription': 'Quản lý thông tin liên hệ của khách hàng',
    'customer.imageGallery': 'Thư viện hình ảnh',
    'customer.imageGalleryDescription': 'Xem và quản lý hình ảnh hồ sơ và cơ sở vật chất của khách hàng',
    'customer.contactPersons': 'Thông tin người liên hệ',
    'customer.contactPersonsDescription': 'Quản lý thông tin chi tiết của các người liên hệ',
    'customer.addContactPerson': 'Thêm người liên hệ',
    'customer.summary': 'Thông tin tóm tắt',
    'customer.summaryInfo': 'Tóm tắt',
    'customer.quickActions': 'Hành động nhanh',
    'customer.createdAt': 'Ngày đăng ký',
    'customer.updatedAt': 'Lần sửa đổi cuối',
    'customer.selectAssignedUser': 'Chọn người phụ trách',

    // 회사 유형 번역
    'customer.companyType.sme': 'Doanh nghiệp vừa và nhỏ',
    'customer.companyType.large': 'Tập đoàn lớn',
    'customer.companyType.startup': 'Startup',
    'customer.companyType.public': 'Cơ quan công',
    'customer.companyType.nonprofit': 'Tổ chức phi lợi nhuận',

    // 고객 등급 번역
    'customer.grade.a': 'Hạng A (VIP)',
    'customer.grade.b': 'Hạng B (Xuất sắc)',
    'customer.grade.c': 'Hạng C (Bình thường)',
    'customer.grade.d': 'Hạng D (Tiêu chuẩn)',
    'customer.grade.e': 'Hạng E (Cơ bản)',

    // 회사명 중복 검사 관련
    'customer.name.duplicate': 'Tên công ty đã tồn tại',
    'customer.name.available': 'Tên công ty có thể sử dụng',
    'customer.name.checkError': 'Lỗi khi kiểm tra tên công ty',
  },
  en: {
    // 앱 공통
    'app.title': 'LN Partners Groupware',
    'app.redirecting': 'Loading...',
    
    // 공통
    login: 'Login',
    register: 'Sign Up',
    logout: 'Logout',
    dashboard: 'Dashboard',
    customers: 'Customers',
    'customers.list': 'Customer List',
    'customers.add': 'Add Customer',
    'customers.voc': 'VOC Management',
    'customers.history': 'Activity History',
    'customers.grades': 'Grade Management',
    'customers.searchAndFilter': 'Search & Filter',
    'customers.searchPlaceholder': 'Search by company name, contact, industry...',
    'customers.allGrades': 'All Grades',
    'customers.gradeA': 'Grade A (VIP)',
    'customers.gradeB': 'Grade B (Excellent)',
    'customers.gradeC': 'Grade C (Regular)',
    'customers.addNew': 'Add New Customer',
    'customers.total': 'Total Customers',
    'customers.contact': 'Contact',
    'customers.industry': 'Industry',
    'customers.registeredDate': 'Registered Date',
    'customers.viewDetails': 'View Details',
    'customers.edit': 'Edit',
    'customers.activityHistory': 'Activity History',
    'customers.noResults': 'No customers match the search criteria.',
    'customers.addFirst': 'Register First Customer',
    'customers.add.description': 'Register new customer information to expand your customer database',
    'customers.add.basicInfo.title': 'Basic Information',
    'customers.add.basicInfo.description': 'Enter customer basic information',
    'customers.add.companyName': 'Company Name',
    'customers.add.companyName.placeholder': 'Enter company name',
    'customers.add.contactName': 'Contact Name',
    'customers.add.contactName.placeholder': 'Enter contact name',
    'customers.add.email': 'Email',
    'customers.add.email.placeholder': 'Enter email address',
    'customers.add.phone': 'Phone',
    'customers.add.phone.placeholder': 'Enter phone number',
    'customers.add.industry': 'Industry',
    'customers.add.industry.placeholder': 'Enter industry',
    'customers.add.grade': 'Customer Grade',
    'customers.add.address': 'Address',
    'customers.add.address.placeholder': 'Enter address',
    'customers.grade.A': 'Grade A (VIP)',
    'customers.grade.B': 'Grade B (Excellent)',
    'customers.grade.C': 'Grade C (Regular)',
    'common.error': 'An error occurred',
    products: 'Products',
    'products.list': 'Product List',
    'products.add': 'Add Product',
    'products.categories': 'Category Management',
    'products.models': 'Model Management',
    'products.competitors': 'Competitor Information',
    'products.inventory': 'Inventory Management',
    sales: 'Sales Management',
    'sales.dashboard': 'Sales Dashboard',
    'sales.opportunities': 'Sales Opportunities',
    'sales.pipeline': 'Sales Pipeline',
    'sales.quotes': 'Quotes',
    'sales.activities': 'Sales Activities',
    'sales.kpi': 'Sales KPI',
    revenue: 'Revenue Management',
    'revenue.dashboard': 'Revenue Dashboard',
    'revenue.record': 'Revenue Record',
    'revenue.quotes': 'Quote Management',
    'revenue.orders': 'Order Management',
    'revenue.payment': 'Payment Management',
    'revenue.statistics': 'Revenue Statistics',
    'revenue.goals': 'Performance vs Goals',
    marketing: 'Marketing Management',
    'marketing.dashboard': 'Marketing Dashboard',
    'marketing.content': 'Content Management',
    'marketing.monitoring': 'Posting Monitoring',
    'marketing.insights': 'Performance Insights',
    'marketing.abtest': 'A/B Test Management',
    'marketing.trends': 'Market Trend Analysis',
    'marketing.engagement': 'Auto Engagement Management',
    'marketing.settings': 'Marketing Settings',
    accounting: 'Accounting Management',
    'accounting.dashboard': 'Accounting Dashboard',
    'accounting.voucher': 'Voucher Management',
    'accounting.ledger': 'Ledger Management',
    'accounting.statements': 'Financial Statements',
    'accounting.assets': 'Asset Management',
    'accounting.tax': 'Tax Management',
    'accounting.budget': 'Budget Management',
    'accounting.reports': 'Accounting Reports',
    'accounting.dashboard.description': 'Get an overview of your entire accounting status at a glance',
    'accounting.totalRevenue': 'Total Revenue',
    'accounting.totalExpenses': 'Total Expenses',
    'accounting.netProfit': 'Net Profit',
    'accounting.profitMargin': 'Profit Margin',
    'accounting.quickActions': 'Quick Actions',
    'accounting.pendingTasks': 'Pending Tasks',
    'accounting.recentTransactions': 'Recent Transactions',
    'accounting.setup': 'Accounting Setup',
    'accounting.setup.description': 'Set up basic accounting information according to Vietnamese accounting standards',
    'accounting.basicInfo': 'Basic Information',
    'accounting.chartOfAccounts': 'Chart of Accounts',
    'accounting.taxSettings': 'Tax Settings',
    'accounting.securitySettings': 'Security Settings',
    'accounting.integrations': 'External Integrations',
    'accounting.companyInfo': 'Company Information',
    'accounting.companyName': 'Company Name',
    'accounting.taxCode': 'Tax Code',
    'accounting.address': 'Address',
    'accounting.representative': 'Representative',
    'accounting.fiscalYear': 'Fiscal Year',
    'accounting.currency': 'Base Currency',
    'accounting.save': 'Save',
    'accounting.accountCode': 'Account Code',
    'accounting.accountName': 'Account Name',
    'accounting.category': 'Category',
    'accounting.status': 'Status',
    'accounting.actions': 'Actions',
    'accounting.active': 'Active',
    'accounting.inactive': 'Inactive',
    'accounting.edit': 'Edit',
    'accounting.vatSettings': 'VAT Settings',
    'accounting.taxType': 'Tax Type',
    'accounting.addTaxType': 'Add New Tax Type',
    'accounting.adminEmail': 'Admin Email',
    'accounting.webhookToken': 'Webhook Verification Token',
    'accounting.twoFactorAuth': 'Enable Two-Factor Authentication',
    'accounting.ipWhitelist': 'Use IP Whitelist',
    'accounting.saveSettings': 'Save Settings',
    'accounting.externalSystems': 'External System Integration',
    'accounting.apiKeyManagement': 'API Key Management',
    'accounting.connected': 'Connected',
    'accounting.error': 'Error',
    'accounting.disconnected': 'Disconnected',
    'accounting.lastSync': 'Last Sync',
    'accounting.apiKey': 'API Key',
    'accounting.normal': 'Normal',

    // 영업 대시보드
    'sales.dashboard.title': 'Sales Dashboard',
    'sales.dashboard.description': 'Get an overview of your sales pipeline and performance metrics at a glance',
    'sales.totalOpportunities': 'Total Opportunities',
    'sales.active': 'Active',
    'sales.conversionRate': 'Conversion Rate',
    'sales.success': 'Won',
    'sales.expectedRevenue': 'Expected Revenue',
    'sales.totalPipelineValue': 'Total Pipeline Value',
    'sales.totalCustomers': 'Customer Count',
    'sales.registeredCustomers': 'Registered Customers',
    'sales.pipeline': 'Sales Pipeline',
    'sales.pipelineDistribution': 'Opportunity Distribution by Stage',
    'sales.recentOpportunities': 'Recent Opportunities',
    'sales.newOpportunities': 'Newly Registered Opportunities',
    'sales.noOpportunities': 'No sales opportunities registered.',
    'sales.quickActions': 'Quick Actions',
    'sales.quickActionsDescription': 'Quickly access frequently used sales features',
    'sales.newOpportunity': 'New Opportunity',
    'sales.opportunityRegistration': 'Register Opportunity',
    'sales.pipelineView': 'Pipeline',
    'sales.pipelineStatus': 'View Progress Status',
    'sales.performanceAnalysis': 'Performance Analysis',
    'sales.kpiCheck': 'Check KPI',
    'sales.stage.prospect': 'Prospect',
    'sales.stage.qualification': 'Qualification',
    'sales.stage.proposal': 'Proposal',
    'sales.stage.negotiation': 'Negotiation',
    'sales.stage.closed_won': 'Closed Won',
    'sales.stage.closed_lost': 'Closed Lost',
    'sales.previousMonth': 'vs previous month',

    // 회계 대시보드 추가 번역
    'accounting.previousMonth': 'vs previous month',
    'accounting.quickActionsDescription': 'Quickly access frequently used accounting features',
    'accounting.pendingTasksDescription': 'Items that require approval or processing',
    'accounting.recentTransactionsDescription': 'Check recent accounting transactions',
    'accounting.pendingVouchers': 'Pending Vouchers',
    'accounting.pendingApproval': 'Pending Approval',
    'accounting.overduePayments': 'Overdue Payments',

    // 고객사 관련 번역
    'customer.add.title': 'Add New Customer',
    'customer.add.description': 'Enter customer information and contact information',
    'customer.createSuccess': 'Customer registered successfully.',
    'customer.createError': 'An error occurred while registering the customer.',
    'customer.grade': 'Customer Grade',
    'customer.gradeSelect': 'Select customer grade',
    'customer.gradeCustomPlaceholder': 'Enter customer grade',
    'customer.grade.vip': 'Grade A (VIP)',
    'customer.grade.excellent': 'Grade B (Excellent)',
    'customer.grade.normal': 'Grade C (Normal)',
    'customer.grade.custom': 'Custom input',

    // 회사 정보 관련 번역
    'company.info.basic': 'Basic Company Information',
    'company.info.description': 'Enter basic information of the customer',
    'company.name': 'Company Name',
    'company.namePlaceholder': 'Enter company name',
    'company.industry': 'Industry',
    'company.industryPlaceholder': 'Enter industry',
    'company.type': 'Company Type',
    'company.typeSelect': 'Select company type',
    'company.typeCustomPlaceholder': 'Enter company type',
    'company.type.small': 'Small Business',
    'company.type.large': 'Large Corporation',
    'company.type.startup': 'Startup',
    'company.type.public': 'Public Institution',
    'company.type.nonprofit': 'Nonprofit Organization',
    'company.type.custom': 'Custom input',

    // 주소 관련 번역
    'address.title': 'Address',
    'address.selectProvince': 'Select Province/City',
    'address.selectDistrict': 'Select District/County',
    'address.selectWard': 'Select Ward/Township',
    'address.detailAddress': 'Enter detailed address',

    // 영업사원 관련 번역
    'sales.person.assigned': 'Sales Representative',
    'sales.person.description': 'Select the sales representative for this customer',
    'sales.person.placeholder': 'Search and select a sales representative',

    // 이미지 관련 번역
    'image.registration': 'Image Registration',
    'image.description': 'Register the customer profile image and facility photos',
    'image.profile': 'Customer Profile Image',
    'image.facility': 'Facility Photos',
    'image.add': 'Add Image',

    // 담당자 관련 번역
    'contact.info': 'Contact Information',
    'contact.description': 'Add customer contacts',
    'contact.person': 'Contact Person',
    'contact.add': 'Add Contact',
    'contact.profileImage': 'Profile Image',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Contact Name',
    'contact.department': 'Department',
    'contact.departmentPlaceholder': 'Department Name',
    'contact.position': 'Position',
    'contact.positionPlaceholder': 'Position',
    'contact.phone': 'Phone Number',
    'contact.phonePlaceholder': 'Phone Number',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Email',
    'contact.birthDate': 'Birth Date',

    // 검색 관련 번역
    'search.salesPerson': 'Search Contact...',

    // 버튼 관련 번역
    'button.cancel': 'Cancel',
    'button.register': 'Register Customer',
    'button.submitting': 'Submitting...',

    // 공통 번역
    'loading': 'Loading...',
    employees: 'Employee Management',
    'employees.dashboard': 'Employee Dashboard',
    'employees.leave': 'Leave Management',
    'employees.salary': 'Salary Management',
    'employees.profile': 'Employee Profile',
    'employees.attendance': 'Attendance Management',
    'employees.evaluation': 'Performance Evaluation',
    'employees.communication': 'Internal Communication',

    settings: 'Settings',
    profile: 'Profile',

    // 로그인 페이지
    'login.title': 'Login',
    'login.description': 'Log in to your account to use the CRM system.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.register.link': "Don't have an account? Sign up",
    'login.success': 'Login successful',
    'login.success.description': 'Redirecting to dashboard.',
    'login.error': 'Login failed',
    'login.error.description': 'Please check your email and password.',
    'login.loading': 'Logging in...',

    // 회원가입 페이지
    'register.title': 'Sign Up',
    'register.description': 'Create a new account to get started with CRM system.',
    'register.name': 'Full Name',
    'register.name.placeholder': 'e.g. John Smith',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.department': 'Department',
    'register.department.sales': 'Sales',
    'register.department.inventory': 'Inventory/Shipping',
    'register.department.marketing': 'Marketing',
    'register.department.accounting': 'Accounting',
    'register.department.support': 'Customer Support',
    'register.department.other': 'Other',
    'register.department.otherInput': 'Enter other department name',
    'register.position': 'Position',
    'register.employeeId': 'Employee ID',
    'register.joinDate': 'Join Date',
    'register.phoneNumber': 'Phone Number',
    'register.address': 'Address',
    'register.address.placeholder': 'e.g. 123 Main Street, New York, NY 10001',
    'register.nationality': 'Nationality',
    'register.nationality.vietnam': 'Vietnam',
    'register.nationality.korea': 'Korea',
    'register.nationality.usa': 'United States',
    'register.nationality.japan': 'Japan',
    'register.nationality.china': 'China',
    'register.nationality.thailand': 'Thailand',
    'register.nationality.other': 'Other',
    'register.birthDate': 'Birth Date',
    'register.visaStatus': 'Visa Status',
    'register.visaStatus.optional': 'Optional (enter only if applicable)',
    'register.emergencyContact': 'Emergency Contact',
    'register.emergencyContact.name': 'Name',
    'register.emergencyContact.relationship': 'Relationship',
    'register.emergencyContact.phone': 'Phone Number',
    'register.skills': 'Skills',
    'register.skills.placeholder': 'e.g. React, Next.js, Node.js, Photoshop, sales, etc',
    'register.experience': 'Experience',
    'register.experience.company': 'Company',
    'register.experience.position': 'Position',
    'register.experience.startDate': 'Start Date',
    'register.experience.endDate': 'End Date',
    'register.experience.description': 'Description',
    'register.submit': 'Sign Up',
    'register.login.link': 'Already have an account? Login',
    'register.addEmergencyContact': 'Add Emergency Contact',
    'register.addExperience': 'Add Experience',
    'register.addSkill': 'Add Skill',
    'register.required': 'Required',
    'register.optional': 'Optional',

    // 공통 텍스트
    'common.success': 'Success',
    'common.error': 'Error',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.add': 'Add',
    'common.select': 'Select',
    'common.notSet': 'Not Set',
    'common.noData': 'No Data',

    // 프로필 관리
    'profile.title': 'Profile Management',
    'profile.description': 'Manage your personal and work information',
    'profile.basicInfo': 'Basic Information',
    'profile.personalInfo': 'Personal Information',
    'profile.workInfo': 'Work Information',
    'profile.updateSuccess': 'Profile updated successfully.',
    'profile.updateError': 'An error occurred while updating the profile.',
    'profile.fetchError': 'An error occurred while fetching profile information.',

    // 비밀번호 강도 및 유효성 검사
    'register.password.strength': 'Password Strength',
    'register.password.strength.weak': 'Weak',
    'register.password.strength.medium': 'Medium',
    'register.password.strength.strong': 'Strong',
    'register.password.requirement.minLength': 'Minimum 8 characters',
    'register.password.requirement.uppercase': 'At least 1 uppercase letter',
    'register.password.requirement.specialChar': 'At least 1 special character',
    'register.password.requirement.match': 'Passwords match',
    'register.email.invalid': 'Invalid email format',
    'register.phone.country': 'Country',
    'register.phone.selectCountry': 'Select country',
    'register.phone.invalid': 'Invalid phone number',

    // 대시보드
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Get an overview of your entire business at a glance.',
    'dashboard.totalCustomers': 'Total Customers',
    'dashboard.activeOpportunities': 'Active Opportunities',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.successRate': 'Success Rate',
    'dashboard.recentCustomers': 'Recent Customers',
    'dashboard.recentCustomers.description': 'List of recently registered customers.',
    'dashboard.opportunities': 'Ongoing Opportunities',
    'dashboard.opportunities.description': 'Major sales opportunities currently in progress.',

    // app/page.js
 'sidebar.companyName': 'LN Partners',
 'sidebar.subTitle': 'Groupware',
 'sidebar.menuTitle': 'Menu',
    'app.title': 'CRM System',
    'app.redirecting': 'Redirecting to login page...',

    // common
    'previousMonth': 'vs previous month',

    // 고객 관련 번역
    'customers.title': 'Customer Management',
    'customers.description': 'Efficiently manage and analyze customer information',
    'customers.addNew': 'Add New Customer',
    'customers.total': 'Total Customers',
    'customers.gradeA': 'Grade A Customers',
    'customers.gradeB': 'Grade B Customers',
    'customers.gradeC': 'Grade C Customers',
    'customers.allGrades': 'All Grades',
    'customers.searchPlaceholder': 'Search by customer name or contact name...',

    // 고객 상세페이지 번역
    'customer.basicInfo': 'Basic Company Information',
    'customer.basicInfoDescription': 'You can check and modify the customer\'s basic information',
    'customer.companyInfo': 'Company Information',
    'customer.companyInfoDescription': 'Basic information of the customer',
    'customer.name': 'Company Name',
    'customer.assignedUser': 'Assigned User',
    'customer.manager': 'Manager',
    'customer.industry': 'Industry',
    'customer.businessType': 'Industry',
    'customer.companyType': 'Company Type',
    'customer.organizationType': 'Organization Type',
    'customer.grade': 'Customer Grade',
    'customer.address': 'Address',
    'customer.email': 'Email',
    'customer.phone': 'Phone Number',
    'customer.contactInfo': 'Contact Information',
    'customer.contactInfoDescription': 'Manage the customer\'s contact information',
    'customer.imageGallery': 'Image Gallery',
    'customer.imageGalleryDescription': 'You can check and manage the customer\'s profile image and facility photos',
    'customer.contactPersons': 'Contact Persons Information',
    'customer.contactPersonsDescription': 'Manage the detailed information of the customer\'s contact persons',
    'customer.addContactPerson': 'Add Contact Person',
    'customer.summary': 'Summary Information',
    'customer.summaryInfo': 'Summary Information',
    'customer.quickActions': 'Quick Actions',
    'customer.createdAt': 'Registration Date',
    'customer.updatedAt': 'Last Modified',
    'customer.selectAssignedUser': 'Select Assigned User',

    // 회사 유형 번역
    'customer.companyType.sme': 'SME',
    'customer.companyType.large': 'Large Enterprise',
    'customer.companyType.startup': 'Startup',
    'customer.companyType.public': 'Public Institution',
    'customer.companyType.nonprofit': 'Nonprofit Organization',

    // 고객 등급 번역
    'customer.grade.a': 'Grade A (VIP)',
    'customer.grade.b': 'Grade B (Excellent)',
    'customer.grade.c': 'Grade C (Normal)',
    'customer.grade.d': 'Grade D (Standard)',
    'customer.grade.e': 'Grade E (Basic)',

    // 회사명 중복 검사 관련
    'customer.name.duplicate': 'Company name already exists',
    'customer.name.available': 'Company name is available',
    'customer.name.checkError': 'Error occurred while checking company name',
  }
}

const translationObject = {
    logout: {
      ko: '로그아웃',
      en: 'Logout',
      vi: 'Đăng xuất'
    },
    profile: {
      ko: '프로필',
      en: 'Profile',
      vi: 'Hồ sơ'
    },
    settings: {
      ko: '설정',
      en: 'Settings',
      vi: 'Cài đặt'
    },
}

const translationObject2 = {
    'customers.grades': {
      ko: '고객 등급',
      en: 'Customer Grades',
      vi: 'Cấp độ khách hàng'
    },

    // Profile Management
    'profile.title': {
      ko: '프로필 관리',
      en: 'Profile Management',
      vi: 'Quản lý hồ sơ'
    },
    'profile.description': {
      ko: '개인정보 및 업무정보를 관리하세요',
      en: 'Manage your personal and work information',
      vi: 'Quản lý thông tin cá nhân và công việc của bạn'
    },
    'profile.manage': {
      ko: '프로필 관리',
      en: 'Manage Profile',
      vi: 'Quản lý hồ sơ'
    },
    'profile.basicInfo': {
      ko: '기본 정보',
      en: 'Basic Information',
      vi: 'Thông tin cơ bản'
    },
    'profile.personalInfo': {
      ko: '개인 정보',
      en: 'Personal Information',
      vi: 'Thông tin cá nhân'
    },
    'profile.workInfo': {
      ko: '업무 정보',
      en: 'Work Information',
      vi: 'Thông tin công việc'
    },
    'profile.updateSuccess': {
      ko: '프로필이 성공적으로 업데이트되었습니다.',
      en: 'Profile updated successfully.',
      vi: 'Hồ sơ đã được cập nhật thành công.'
    },
    'profile.updateError': {
      ko: '프로필 업데이트 중 오류가 발생했습니다.',
      en: 'An error occurred while updating the profile.',
      vi: 'Đã xảy ra lỗi khi cập nhật hồ sơ.'
    },
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ko')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'ko'
    setLanguage(savedLanguage)
  }, [])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('language', newLanguage)
  }

  const cycleLanguage = () => {
    const languages = ['ko', 'en', 'vi']
    const currentIndex = languages.indexOf(language)
    const nextIndex = (currentIndex + 1) % languages.length
    changeLanguage(languages[nextIndex])
  }

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, cycleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}