name: Replit-AI → Windows-Docker 자동 배포

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      # 1) 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Docker 이미지 빌드 및 컨테이너 실행
      - name: Build and Run Docker Container
        shell: powershell
        run: |
          cd ${{ github.workspace }}

          # (a) 기존 컨테이너가 실행 중이면 중지 및 삭제
          if (docker ps -q --filter "name=lngw2025_v2_server") {
            docker stop lngw2025_v2_server
            docker rm lngw2025_v2_server
          }

          # (b) 이미지 빌드
          docker build -t lngw-image:latest .

          # (c) 컨테이너 실행: Windows MySQL(host.docker.internal)로 연결
          docker run -d `
            --name lngw2025_v2_server `
            -e NODE_ENV=production `
            -e DB_HOST=host.docker.internal `
            -e DB_PORT=3306 `
            -e DB_NAME=lngw2025_db `
            -e DB_USER=appuser `
            -e DB_PASSWORD=gywo9988!@ `
            -e PORT=4000 `
            -p 3000:4000 `
            --restart always `
            lngw-image:latest

      # 3) 배포 완료 메시지 출력
      - name: Deployment Complete
        shell: powershell
        run: Write-Host "✅ Deployment finished on Windows Docker runner."
