name: Replit-AI → Windows-Docker 자동 배포

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Run Docker Container
        shell: powershell
        run: |
          cd ${{ github.workspace }}

          # 기존 컨테이너 강제 삭제
          $cid = docker ps -aq --filter "name=lngw2025_v2_server"
          if ($cid) {
            docker rm -f $cid
          }

          # Docker 데몬 상태 확인
          docker version

          # 이미지 빌드
          docker build -t lngw-image:latest .

          # 컨테이너 실행
          docker run -d `
            --name lngw2025_v2_server `
            -e NODE_ENV=production `
            -e DB_HOST=host.docker.internal `
            -e DB_PORT=3306 `
            -e DB_NAME=lngw2025_db `
            -e DB_USER=appuser `
            -e DB_PASSWORD=gywo9988!@ `
            -e PORT=4000 `
            -p 3000:4000 `
            --restart always `
            lngw-image:latest

      - name: Deployment Complete
        shell: powershell
        run: Write-Host "✅ Deployment finished on Windows Docker runner."
