# ──────────────────────────────────────────────────────────────────────────
# .github/workflows/deploy.yml
# main 브랜치 Push → 로컬 Webhook 서버로 POST 요청 → 배포 스크립트 실행
# ──────────────────────────────────────────────────────────────────────────

name: Auto-Deploy to Local Windows

on:
  push:
    branches:
      - main

jobs:
  notify-local:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook on Local Server
        run: |
          # 배포를 위해 HTTP POST 요청을 로컬 서버로 전송
          # 포트포워딩(공유기, 방화벽 설정) 후, 반드시 gw.lnpartners.biz:7000으로 접근 가능해야 함
          curl -X POST "http://gw.lnpartners.biz:7000/webhook"
