version: "3.8"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-ssl
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=admin@yourdomain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - proxy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lngw2025_v2_server
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=lngw2025_db
      - DB_USER=appuser
      - DB_PASSWORD=gywo9988!@
      - PORT=4000
      - VIRTUAL_HOST=yourdomain.com
      - LETSENCRYPT_HOST=yourdomain.com
      - LETSENCRYPT_EMAIL=admin@yourdomain.com
    expose:
      - "4000"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge
